import os
import sys
import json
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import List, Optional

# Add root path for module resolution
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
from storage.vector_store import VectorStoreManager
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="Google Photos Discovery Engine API")

from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins
    allow_credentials=True,
    allow_methods=["*"],  # Allows all methods
    allow_headers=["*"],  # Allows all headers
)

# Serve Frontend
frontend_path = os.path.join(os.path.dirname(__file__), "..", "frontend")
app.mount("/static", StaticFiles(directory=frontend_path), name="static")

@app.get("/")
def serve_frontend():
    return FileResponse(os.path.join(frontend_path, "index.html"))
store = VectorStoreManager()
client = Groq(api_key=os.environ.get("GROQ_API_KEY", "mock_key"))

class SearchQuery(BaseModel):
    query: str
    n_results: int = 5
    filter_stage: Optional[str] = None

class AskQuery(BaseModel):
    question: str

@app.get("/clusters")
def get_clusters():
    """Returns the ranked opportunity list generated by Phase 5."""
    report_path = os.path.join(store.base_dir, "analysis", "opportunity_report.json")
    if not os.path.exists(report_path):
        return {"status": "pending", "message": "Cluster report not yet generated."}
        
    with open(report_path, 'r', encoding='utf-8') as f:
        return json.load(f)

@app.get("/search")
def semantic_search(q: str, n: int = 5, stage: Optional[str] = None):
    """Embeds query and searches the vector store."""
    try:
        results = store.search(query=q, n_results=n, filter_stage=stage)
        return {"query": q, "results": results}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

from collections import Counter, defaultdict

@app.get("/stats")
def get_stats():
    """Returns analytics for the charts."""
    try:
        results = store.collection.get(include=["metadatas"])
        metadatas = results.get("metadatas", [])
        
        if not metadatas:
            # Return mock data for UI demonstration until extraction finishes
            return {
                "failure_stages": {"expression": 1900, "interpretation": 1150, "evaluation": 980, "recovery": 420},
                "photo_types_by_stage": {
                    "expression": {"screenshot": 1500, "pet": 200, "person": 200},
                    "interpretation": {"screenshot": 400, "pet": 450, "person": 300},
                    "evaluation": {"screenshot": 100, "pet": 380, "person": 500},
                    "recovery": {"screenshot": 150, "pet": 50, "person": 220}
                }
            }
            
        stage_counts = Counter()
        photo_by_stage = defaultdict(Counter)
        
        for meta in metadatas:
            stage = meta.get("failure_stage", "unknown")
            ptype = meta.get("photo_type", "unknown")
            stage_counts[stage] += 1
            photo_by_stage[stage][ptype] += 1
            
        return {
            "failure_stages": dict(stage_counts),
            "photo_types_by_stage": {k: dict(v) for k, v in photo_by_stage.items()}
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ask")
def ask_natural_language(query: AskQuery):
    """
    Translates PM natural language into a query, searches the store, 
    and synthesizes an answer strictly from evidence.
    """
    try:
        # Step 1: Semantic search on the raw question
        search_results = store.search(query=query.question, n_results=40)
        
        # Extract the documents and metadata
        documents = search_results.get("documents", [[]])[0]
        metadatas = search_results.get("metadatas", [[]])[0]
        
        # Filter records based on some simple mapping if requested (mock query interpretation)
        intent = "General retrieval inquiry"
        
        # Build records payload
        records_payload = []
        source_counts = Counter()
        
        for doc, meta in zip(documents, metadatas):
            source_counts[meta.get("source", "unknown")] += 1
            
            # Reconstruct list fields that were stored as JSON strings in ChromaDB metadata
            try:
                mem_present = json.loads(meta.get("memory_cues_present", "[]"))
            except:
                mem_present = []
                
            try:
                mem_missing = json.loads(meta.get("memory_cues_missing", "[]"))
            except:
                mem_missing = []
                
            records_payload.append({
                "record_id": meta.get("id"),
                "source": meta.get("source"),
                "source_url": "internal_db",
                "memory_cues_present": mem_present,
                "memory_cues_missing": mem_missing,
                "search_behavior": meta.get("search_behavior"),
                "failure_stage": meta.get("failure_stage"),
                "outcome": meta.get("outcome"),
                "verbatim_quote": meta.get("verbatim_quote")
            })

        # Step 2: Use Groq to synthesize an answer based strictly on the context
        # Truncate to top 5 for the LLM to avoid rate limits and confusion
        evidence_context = json.dumps(records_payload[:5], indent=2)

        prompt = f"""Research question:
{query.question}

Evidence:
{evidence_context}

Return concise Markdown with:

## Key Finding
## What Users Remember
## What They Forget
## Retrieval Failure
## Supporting Evidence
## Evidence Gaps"""

        try:
            system_msg = "You are a product research analyst analyzing real Google Photos user evidence.\n\nAnswer ONLY from the evidence provided below.\n\nDo not use outside knowledge.\nDo not invent user complaints.\nDo not invent quotes.\nDo not invent statistics.\n\nFor each finding:\n- explain what the evidence shows\n- distinguish what users remember from what they forget\n- identify the retrieval failure if supported\n- cite the record IDs\n\nIf the evidence does not support a conclusion, explicitly say so."
            
            try:
                # Try Groq first
                res = client.chat.completions.create(
                    messages=[
                        {"role": "system", "content": system_msg},
                        {"role": "user", "content": prompt}
                    ],
                    model="qwen/qwen3.8-27b",
                    temperature=0.0,
                    max_tokens=800
                )
                analysis_text = res.choices[0].message.content
            except Exception as groq_err:
                print(f"Groq failed ({groq_err}), falling back to Gemini...")
                # Fallback to Gemini REST API to bypass SDK/Cloudflare issues on Railway
                import urllib.request
                import json
                gemini_key = os.environ.get("GEMINI_API_KEY_1")
                if not gemini_key:
                    raise Exception(f"Groq failed with '{groq_err}' and no Gemini key available for fallback.")
                
                url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={gemini_key}"
                data = json.dumps({
                    "contents": [{"parts": [{"text": system_msg + "\n\n" + prompt}]}]
                }).encode("utf-8")
                req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
                with urllib.request.urlopen(req, timeout=30) as response:
                    resp_data = json.loads(response.read().decode())
                    analysis_text = resp_data["candidates"][0]["content"]["parts"][0]["text"]

            analysis_dict = {"markdown_analysis": analysis_text}
            
        except Exception as api_err:
            print(f"Synthesis LLM Error: {api_err}")
            analysis_dict = {
                "markdown_analysis": f"Failed to generate synthesis due to LLM error: {api_err}"
            }

        return {
            "question": query.question,
            "query_interpretation": {
                "intent": intent,
                "filters": [],
                "semantic_query": query.question
            },
            "evidence": {
                "records_found": len(documents),
                "records_used": len(documents),
                "sources": dict(source_counts)
            },
            "records": records_payload,
            "analysis": analysis_dict
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
